# Generated by Django 3.2.3 on 2022-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_orders_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='initial_price',
            field=models.IntegerField(default=1),
        ),
    ]
