# Generated by Django 3.2.3 on 2022-10-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_auto_20221025_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.IntegerField(default=1),
        ),
    ]
